baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Screaming Goat Collectibles"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
images = ["img/129b50b6-4177-476e-81dd-96206148a46a.jpg"]